from datetime import datetime
from typing import Protocol

from ..models import Conversation, Message, UsageRecord, UsageSummary, User, UserWithSecret


class UserStore(Protocol):
    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def count(self) -> int: ...
    async def create_user(
        self, username: str, password_hash: str, is_admin: bool, token_budget: int | None = None
    ) -> User: ...
    async def set_token_budget(self, user_id: str, token_budget: int | None) -> bool: ...
    async def get_user(self, user_id: str) -> User | None: ...
    async def get_by_username(self, username: str) -> UserWithSecret | None: ...
    async def list_users(self) -> list[User]: ...
    async def delete_user(self, user_id: str) -> bool: ...


class ChatStore(Protocol):
    """Chat history and usage. Knows nothing about users beyond the opaque user_id."""

    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def create_conversation(self, user_id: str, title: str) -> Conversation: ...
    async def list_conversations(self, user_id: str) -> list[Conversation]: ...
    async def list_all_conversations(self) -> list[Conversation]: ...
    async def get_conversation(self, conversation_id: str) -> Conversation | None: ...
    async def touch_conversation(self, conversation_id: str, *, title: str | None = None) -> None: ...
    async def delete_conversation(self, conversation_id: str) -> None: ...
    async def append_message(self, message: Message) -> None: ...
    async def list_messages(self, conversation_id: str) -> list[Message]: ...
    async def record_usage(self, record: UsageRecord) -> None: ...
    async def usage_summary(self, *, since: datetime | None = None) -> list[UsageSummary]: ...
    async def usage_for_user(self, user_id: str, *, since: datetime | None = None) -> UsageSummary: ...
